# Generated by Django 3.0.4 on 2020-08-03 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=320)),
                ('address', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'CONTACTS',
            },
        ),
        migrations.CreateModel(
            name='crop_farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=320)),
                ('region', models.CharField(choices=[('Araria', 'Araria'), ('Arwal', 'Arwal'), ('Aurangabad', 'Aurangabad'), ('Banka', 'Banka'), ('Begusarai', 'Begusarai'), ('Bhagalpur', 'Bhagalpur'), ('Bhojpur', 'Bhojpur'), ('Buxar', 'Buxar'), ('Darbhanga', 'Darbhanga'), ('East_champaran', 'East_Champaran'), ('Gaya', 'Gaya'), ('Gopalganj', 'Gopalganj'), ('Jamui', 'Jamui'), ('Jehanabad', 'Jehanabad'), ('Khagaria', 'Khagaria'), ('Kishanganj', 'Kishanganj'), ('Kaimur', 'Kaimur'), ('Katihar', 'Katihar'), ('Lakshisarai', 'Lakshisarai'), ('Madhubani', 'Madhubani'), ('Munger', 'Munger'), ('Madhepura', 'Madhepura'), ('Muzaffarpur', 'Muzaffarpur'), ('Nalanda', 'Nalanda'), ('Nawada', 'Nawada'), ('Patna', 'Patna'), ('Purnia', 'Purnia'), ('Rohtas', 'Rohtas'), ('Saharsa', 'Saharsa'), ('Samastipur', 'Samastipur'), ('Sheohar', 'Sheohar'), ('Sheikhpura', 'Sheikhpura'), ('Saran', 'Saran'), ('Sitamarhi', 'Sitamarhi'), ('Supaul', 'Supaul'), ('Siwan', 'Siwan'), ('Vaishali', 'Vaishali'), ('West_champaran', 'West_Champaran')], max_length=200)),
                ('crop_type', models.CharField(choices=[('Kharif', 'Kharif'), ('Rabi', 'Rabi')], max_length=200)),
                ('crop_name', models.CharField(max_length=200)),
                ('seed_type', models.CharField(choices=[('Hybrid', 'Hybrid'), ('Local', 'Local')], max_length=200)),
                ('crop_year', models.CharField(choices=[('2019', '2019'), ('2020', '2020')], max_length=200)),
                ('area', models.BigIntegerField()),
                ('days', models.BigIntegerField()),
                ('irrigation', models.FloatField()),
                ('fertilizers', models.BigIntegerField()),
                ('pesticides', models.BigIntegerField()),
                ('avg_temp', models.FloatField()),
                ('cost', models.FloatField()),
                ('msp', models.FloatField()),
                ('production', models.BigIntegerField()),
                ('approval_status', models.CharField(choices=[('Approved', 'Approved'), ('Notapproved', 'Notapproved')], max_length=200)),
            ],
            options={
                'verbose_name_plural': 'FARMER CROP DATA',
            },
        ),
        migrations.CreateModel(
            name='farm_science_expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Araria', 'Araria'), ('Arwal', 'Arwal'), ('Aurangabad', 'Aurangabad'), ('Banka', 'Banka'), ('Begusarai', 'Begusarai'), ('Bhagalpur', 'Bhagalpur'), ('Bhojpur', 'Bhojpur'), ('Buxar', 'Buxar'), ('Darbhanga', 'Darbhanga'), ('East_champaran', 'East_Champaran'), ('Gaya', 'Gaya'), ('Gopalganj', 'Gopalganj'), ('Jamui', 'Jamui'), ('Jehanabad', 'Jehanabad'), ('Khagaria', 'Khagaria'), ('Kishanganj', 'Kishanganj'), ('Kaimur', 'Kaimur'), ('Katihar', 'Katihar'), ('Lakshisarai', 'Lakshisarai'), ('Madhubani', 'Madhubani'), ('Munger', 'Munger'), ('Madhepura', 'Madhepura'), ('Muzaffarpur', 'Muzaffarpur'), ('Nalanda', 'Nalanda'), ('Nawada', 'Nawada'), ('Patna', 'Patna'), ('Purnia', 'Purnia'), ('Rohtas', 'Rohtas'), ('Saharsa', 'Saharsa'), ('Samastipur', 'Samastipur'), ('Sheohar', 'Sheohar'), ('Sheikhpura', 'Sheikhpura'), ('Saran', 'Saran'), ('Sitamarhi', 'Sitamarhi'), ('Supaul', 'Supaul'), ('Siwan', 'Siwan'), ('Vaishali', 'Vaishali'), ('West_champaran', 'West_Champaran')], max_length=200)),
                ('area', models.FloatField()),
                ('crop_type', models.CharField(choices=[('Kharif', 'Kharif'), ('Rabi', 'Rabi')], max_length=200)),
                ('crop_name', models.CharField(max_length=200)),
                ('seed_type', models.CharField(choices=[('Hybrid', 'Hybrid'), ('Local', 'Local')], max_length=200)),
                ('days', models.BigIntegerField()),
                ('irrigation', models.FloatField()),
                ('fertilizers', models.BigIntegerField()),
                ('pesticides', models.BigIntegerField()),
                ('cost', models.FloatField()),
                ('production', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'FARM SCIENTIST CROP DATA',
            },
        ),
        migrations.CreateModel(
            name='feedback_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('aadhar', models.BigIntegerField()),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=320)),
                ('feedback', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'FEEDBACKS',
            },
        ),
        migrations.CreateModel(
            name='machine_learning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Araria', 'Araria'), ('Arwal', 'Arwal'), ('Aurangabad', 'Aurangabad'), ('Banka', 'Banka'), ('Begusarai', 'Begusarai'), ('Bhagalpur', 'Bhagalpur'), ('Bhojpur', 'Bhojpur'), ('Buxar', 'Buxar'), ('Darbhanga', 'Darbhanga'), ('East_champaran', 'East_Champaran'), ('Gaya', 'Gaya'), ('Gopalganj', 'Gopalganj'), ('Jamui', 'Jamui'), ('Jehanabad', 'Jehanabad'), ('Khagaria', 'Khagaria'), ('Kishanganj', 'Kishanganj'), ('Kaimur', 'Kaimur'), ('Katihar', 'Katihar'), ('Lakshisarai', 'Lakshisarai'), ('Madhubani', 'Madhubani'), ('Munger', 'Munger'), ('Madhepura', 'Madhepura'), ('Muzaffarpur', 'Muzaffarpur'), ('Nalanda', 'Nalanda'), ('Nawada', 'Nawada'), ('Patna', 'Patna'), ('Purnia', 'Purnia'), ('Rohtas', 'Rohtas'), ('Saharsa', 'Saharsa'), ('Samastipur', 'Samastipur'), ('Sheohar', 'Sheohar'), ('Sheikhpura', 'Sheikhpura'), ('Saran', 'Saran'), ('Sitamarhi', 'Sitamarhi'), ('Supaul', 'Supaul'), ('Siwan', 'Siwan'), ('Vaishali', 'Vaishali'), ('West_champaran', 'West_Champaran')], max_length=200)),
                ('crop_type', models.CharField(choices=[('Kharif', 'Kharif'), ('Rabi', 'Rabi')], max_length=200)),
                ('crop_name', models.CharField(max_length=200)),
                ('crop_year', models.CharField(choices=[('2019', '2019'), ('2020', '2020')], max_length=200)),
                ('month', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=200)),
                ('area', models.FloatField()),
                ('avg_temp', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.BigIntegerField()),
                ('production', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'ML DATA',
            },
        ),
        migrations.CreateModel(
            name='registrationdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Araria', 'Araria'), ('Arwal', 'Arwal'), ('Aurangabad', 'Aurangabad'), ('Banka', 'Banka'), ('Begusarai', 'Begusarai'), ('Bhagalpur', 'Bhagalpur'), ('Bhojpur', 'Bhojpur'), ('Buxar', 'Buxar'), ('Darbhanga', 'Darbhanga'), ('East_champaran', 'East_Champaran'), ('Gaya', 'Gaya'), ('Gopalganj', 'Gopalganj'), ('Jamui', 'Jamui'), ('Jehanabad', 'Jehanabad'), ('Khagaria', 'Khagaria'), ('Kishanganj', 'Kishanganj'), ('Kaimur', 'Kaimur'), ('Katihar', 'Katihar'), ('Lakshisarai', 'Lakshisarai'), ('Madhubani', 'Madhubani'), ('Munger', 'Munger'), ('Madhepura', 'Madhepura'), ('Muzaffarpur', 'Muzaffarpur'), ('Nalanda', 'Nalanda'), ('Nawada', 'Nawada'), ('Patna', 'Patna'), ('Purnia', 'Purnia'), ('Rohtas', 'Rohtas'), ('Saharsa', 'Saharsa'), ('Samastipur', 'Samastipur'), ('Sheohar', 'Sheohar'), ('Sheikhpura', 'Sheikhpura'), ('Saran', 'Saran'), ('Sitamarhi', 'Sitamarhi'), ('Supaul', 'Supaul'), ('Siwan', 'Siwan'), ('Vaishali', 'Vaishali'), ('West_champaran', 'West_Champaran')], max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('aadhar', models.BigIntegerField()),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=320)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'FARMER DATA',
            },
        ),
    ]
